#ifndef BIT_BAND
#define BIT_BAND

#include "stm32f1xx.h"

/* 位带区转位带别名区地址 */
#define BITBAND(addr, bitnum)       ((addr & 0xF0000000) + 0x02000000) + \
                                    ((addr & 0x000FFFFF) << 5) + (bitnum << 2)
#define MEM_ADDR(addr)              (*((volatile uint32_t *)(addr)))
#define BIT_ADDR(addr, bitnum)      MEM_ADDR(BITBAND(addr, bitnum))

/* IO口输出地址映射 */
#define GPIOA_ODR_Addr    (GPIOA_BASE + 12) //0x4001080C 
#define GPIOB_ODR_Addr    (GPIOB_BASE + 12) //0x40010C0C 
#define GPIOC_ODR_Addr    (GPIOC_BASE + 12) //0x4001100C 
#define GPIOD_ODR_Addr    (GPIOD_BASE + 12) //0x4001140C 
#define GPIOE_ODR_Addr    (GPIOE_BASE + 12) //0x4001180C 
#define GPIOF_ODR_Addr    (GPIOF_BASE + 12) //0x40011A0C    
#define GPIOG_ODR_Addr    (GPIOG_BASE + 12) //0x40011E0C    
/* IO口输入地址映射 */
#define GPIOA_IDR_Addr    (GPIOA_BASE + 8) //0x40010808 
#define GPIOB_IDR_Addr    (GPIOB_BASE + 8) //0x40010C08 
#define GPIOC_IDR_Addr    (GPIOC_BASE + 8) //0x40011008 
#define GPIOD_IDR_Addr    (GPIOD_BASE + 8) //0x40011408 
#define GPIOE_IDR_Addr    (GPIOE_BASE + 8) //0x40011808 
#define GPIOF_IDR_Addr    (GPIOF_BASE + 8) //0x40011A08 
#define GPIOG_IDR_Addr    (GPIOG_BASE + 8) //0x40011E08 

/* 输出 */
#define PAout(n)   BIT_ADDR(GPIOA_ODR_Addr, n)
#define PBout(n)   BIT_ADDR(GPIOB_ODR_Addr, n)
#define PCout(n)   BIT_ADDR(GPIOC_ODR_Addr, n)
#define PDout(n)   BIT_ADDR(GPIOD_ODR_Addr, n)
#define PEout(n)   BIT_ADDR(GPIOE_ODR_Addr, n)
#define PFout(n)   BIT_ADDR(GPIOF_ODR_Addr, n) 
#define PGout(n)   BIT_ADDR(GPIOG_ODR_Addr, n)
/* 输入 */
#define PAin(n)    BIT_ADDR(GPIOA_IDR_Addr, n)
#define PBin(n)    BIT_ADDR(GPIOB_IDR_Addr, n)
#define PCin(n)    BIT_ADDR(GPIOC_IDR_Addr, n)
#define PDin(n)    BIT_ADDR(GPIOD_IDR_Addr, n)
#define PEin(n)    BIT_ADDR(GPIOE_IDR_Addr, n)
#define PFin(n)    BIT_ADDR(GPIOF_IDR_Addr, n)
#define PGin(n)    BIT_ADDR(GPIOG_IDR_Addr, n)


#define PA0_OUT     PAout(0)
#define PA1_OUT     PAout(1)
#define PA2_OUT     PAout(2)
#define PA3_OUT     PAout(3)
#define PA4_OUT     PAout(4)
#define PA5_OUT     PAout(5)
#define PA6_OUT     PAout(6)
#define PA7_OUT     PAout(7)
#define PA8_OUT     PAout(8)
#define PA9_OUT     PAout(9)
#define PA10_OUT    PAout(10)
#define PA11_OUT    PAout(11)
#define PA12_OUT    PAout(12)
#define PA13_OUT    PAout(13)
#define PA14_OUT    PAout(14)
#define PA15_OUT    PAout(15)

#define PB0_OUT     PBout(0)
#define PB1_OUT     PBout(1)
#define PB2_OUT     PBout(2)
#define PB3_OUT     PBout(3)
#define PB4_OUT     PBout(4)
#define PB5_OUT     PBout(5)
#define PB6_OUT     PBout(6)
#define PB7_OUT     PBout(7)
#define PB8_OUT     PBout(8)
#define PB9_OUT     PBout(9)
#define PB10_OUT    PBout(10)
#define PB11_OUT    PBout(11)
#define PB12_OUT    PBout(12)
#define PB13_OUT    PBout(13)
#define PB14_OUT    PBout(14)
#define PB15_OUT    PBout(15)

#define PC0_OUT     PCout(0)
#define PC1_OUT     PCout(1)
#define PC2_OUT     PCout(2)
#define PC3_OUT     PCout(3)
#define PC4_OUT     PCout(4)
#define PC5_OUT     PCout(5)
#define PC6_OUT     PCout(6)
#define PC7_OUT     PCout(7)
#define PC8_OUT     PCout(8)
#define PC9_OUT     PCout(9)
#define PC10_OUT    PCout(10)
#define PC11_OUT    PCout(11)
#define PC12_OUT    PCout(12)
#define PC13_OUT    PCout(13)
#define PC14_OUT    PCout(14)
#define PC15_OUT    PCout(15)

#define PD0_OUT     PDout(0)
#define PD1_OUT     PDout(1)
#define PD2_OUT     PDout(2)
#define PD3_OUT     PDout(3)
#define PD4_OUT     PDout(4)
#define PD5_OUT     PDout(5)
#define PD6_OUT     PDout(6)
#define PD7_OUT     PDout(7)
#define PD8_OUT     PDout(8)
#define PD9_OUT     PDout(9)
#define PD10_OUT    PDout(10)
#define PD11_OUT    PDout(11)
#define PD12_OUT    PDout(12)
#define PD13_OUT    PDout(13)
#define PD14_OUT    PDout(14)
#define PD15_OUT    PDout(15)

#define PE0_OUT     PEout(0)
#define PE1_OUT     PEout(1)
#define PE2_OUT     PEout(2)
#define PE3_OUT     PEout(3)
#define PE4_OUT     PEout(4)
#define PE5_OUT     PEout(5)
#define PE6_OUT     PEout(6)
#define PE7_OUT     PEout(7)
#define PE8_OUT     PEout(8)
#define PE9_OUT     PEout(9)
#define PE10_OUT    PEout(10)
#define PE11_OUT    PEout(11)
#define PE12_OUT    PEout(12)
#define PE13_OUT    PEout(13)
#define PE14_OUT    PEout(14)
#define PE15_OUT    PEout(15)

#define PF0_OUT     PFout(0)
#define PF1_OUT     PFout(1)
#define PF2_OUT     PFout(2)
#define PF3_OUT     PFout(3)
#define PF4_OUT     PFout(4)
#define PF5_OUT     PFout(5)
#define PF6_OUT     PFout(6)
#define PF7_OUT     PFout(7)
#define PF8_OUT     PFout(8)
#define PF9_OUT     PFout(9)
#define PF10_OUT    PFout(10)
#define PF11_OUT    PFout(11)
#define PF12_OUT    PFout(12)
#define PF13_OUT    PFout(13)
#define PF14_OUT    PFout(14)
#define PF15_OUT    PFout(15)

#define PG0_OUT     PGout(0)
#define PG1_OUT     PGout(1)
#define PG2_OUT     PGout(2)
#define PG3_OUT     PGout(3)
#define PG4_OUT     PGout(4)
#define PG5_OUT     PGout(5)
#define PG6_OUT     PGout(6)
#define PG7_OUT     PGout(7)
#define PG8_OUT     PGout(8)
#define PG9_OUT     PGout(9)
#define PG10_OUT    PGout(10)
#define PG11_OUT    PGout(11)
#define PG12_OUT    PGout(12)
#define PG13_OUT    PGout(13)
#define PG14_OUT    PGout(14)
#define PG15_OUT    PGout(15)

#define PA0_IN     PAin(0)
#define PA1_IN     PAin(1)
#define PA2_IN     PAin(2)
#define PA3_IN     PAin(3)
#define PA4_IN     PAin(4)
#define PA5_IN     PAin(5)
#define PA6_IN     PAin(6)
#define PA7_IN     PAin(7)
#define PA8_IN     PAin(8)
#define PA9_IN     PAin(9)
#define PA10_IN    PAin(10)
#define PA11_IN    PAin(11)
#define PA12_IN    PAin(12)
#define PA13_IN    PAin(13)
#define PA14_IN    PAin(14)
#define PA15_IN    PAin(15)

#define PB0_IN     PBin(0)
#define PB1_IN     PBin(1)
#define PB2_IN     PBin(2)
#define PB3_IN     PBin(3)
#define PB4_IN     PBin(4)
#define PB5_IN     PBin(5)
#define PB6_IN     PBin(6)
#define PB7_IN     PBin(7)
#define PB8_IN     PBin(8)
#define PB9_IN     PBin(9)
#define PB10_IN    PBin(10)
#define PB11_IN    PBin(11)
#define PB12_IN    PBin(12)
#define PB13_IN    PBin(13)
#define PB14_IN    PBin(14)
#define PB15_IN    PBin(15)

#define PC0_IN     PCin(0)
#define PC1_IN     PCin(1)
#define PC2_IN     PCin(2)
#define PC3_IN     PCin(3)
#define PC4_IN     PCin(4)
#define PC5_IN     PCin(5)
#define PC6_IN     PCin(6)
#define PC7_IN     PCin(7)
#define PC8_IN     PCin(8)
#define PC9_IN     PCin(9)
#define PC10_IN    PCin(10)
#define PC11_IN    PCin(11)
#define PC12_IN    PCin(12)
#define PC13_IN    PCin(13)
#define PC14_IN    PCin(14)
#define PC15_IN    PCin(15)

#define PD0_IN     PDin(0)
#define PD1_IN     PDin(1)
#define PD2_IN     PDin(2)
#define PD3_IN     PDin(3)
#define PD4_IN     PDin(4)
#define PD5_IN     PDin(5)
#define PD6_IN     PDin(6)
#define PD7_IN     PDin(7)
#define PD8_IN     PDin(8)
#define PD9_IN     PDin(9)
#define PD10_IN    PDin(10)
#define PD11_IN    PDin(11)
#define PD12_IN    PDin(12)
#define PD13_IN    PDin(13)
#define PD14_IN    PDin(14)
#define PD15_IN    PDin(15)

#define PE0_IN     PEin(0)
#define PE1_IN     PEin(1)
#define PE2_IN     PEin(2)
#define PE3_IN     PEin(3)
#define PE4_IN     PEin(4)
#define PE5_IN     PEin(5)
#define PE6_IN     PEin(6)
#define PE7_IN     PEin(7)
#define PE8_IN     PEin(8)
#define PE9_IN     PEin(9)
#define PE10_IN    PEin(10)
#define PE11_IN    PEin(11)
#define PE12_IN    PEin(12)
#define PE13_IN    PEin(13)
#define PE14_IN    PEin(14)
#define PE15_IN    PEin(15)

#define PF0_IN     PFin(0)
#define PF1_IN     PFin(1)
#define PF2_IN     PFin(2)
#define PF3_IN     PFin(3)
#define PF4_IN     PFin(4)
#define PF5_IN     PFin(5)
#define PF6_IN     PFin(6)
#define PF7_IN     PFin(7)
#define PF8_IN     PFin(8)
#define PF9_IN     PFin(9)
#define PF10_IN    PFin(10)
#define PF11_IN    PFin(11)
#define PF12_IN    PFin(12)
#define PF13_IN    PFin(13)
#define PF14_IN    PFin(14)
#define PF15_IN    PFin(15)

#define PG0_IN     PGin(0)
#define PG1_IN     PGin(1)
#define PG2_IN     PGin(2)
#define PG3_IN     PGin(3)
#define PG4_IN     PGin(4)
#define PG5_IN     PGin(5)
#define PG6_IN     PGin(6)
#define PG7_IN     PGin(7)
#define PG8_IN     PGin(8)
#define PG9_IN     PGin(9)
#define PG10_IN    PGin(10)
#define PG11_IN    PGin(11)
#define PG12_IN    PGin(12)
#define PG13_IN    PGin(13)
#define PG14_IN    PGin(14)
#define PG15_IN    PGin(15)

#endif
